@startuml
!theme vibrant

title "ניהול משימות / תזמון אירועים"

start
:הכותב ניגש למנהל המשימות;
:המערכת מציגה רשימת משימות;

if (הוספת משימה חדשה?) then (כן)
    :הכותב לוחץ "הוסף משימה";
    :המערכת מציגה טופס;
    :הכותב ממלא פרטי משימה (סוג, יעד, תאריך);
    :הכותב שומר את המשימה;
    :המערכת מאמתת את הקלט;
    :המשימה נוספת לרשימה;
else if (עריכת משימה קיימת?) then (כן)
    :הכותב בוחר משימה לעריכה;
    :הכותב משנה את פרטי המשימה;
    :הכותב שומר את השינויים;
else (מחיקת משימה?)
    :הכותב בוחר משימה למחיקה;
    :המערכת מבקשת אישור;
    :הכותב מאשר;
    :המשימה נמחקת מהרשימה;
endif

stop

@enduml
