@startuml
!pragma useVerticalIf on

title WR-UC-01: אימות משתמש (מבוסס אלגוריתם)

start
:המערכת מציגה מסך התחברות;

if (המשתמש לא רשום?) is (כן) then
    :לחץ על כפתור ההרשמה;

repeat :מלא את שדות שם, אימייל וסיסמה;
    :לחץ על כפתור ההרשמה (אישור);
repeat while (קלט תקין?) is (לא) not (כן)

    

    
        
else
    repeat :מלא שדות אימייל וסיסמה;
        :לחץ על כפתור ההתחברות;
    repeat while (קלט אינו תקין (פרטי התחברות שגויים)?) is (לא) not (כן)
    :הצגת הודעה מתאימה (קלט תקין);
    :מעבר למסך הבית (דשבורד);
    stop
endif


@enduml
