@startuml
!theme vibrant

title פעילויות פיקוח על תוכן

start
:גישה לרשימת הדיווחים על תוכן;
:בחירת דיווח לבדיקה;
:צפייה בתוכן המדווח;

if (האם התוכן מפר מדיניות?) then (כן)
  partition "בחירת פעולת מחיקה/אזהרה" {
    :בחירת הפעולה הנדרשת (הסרה, השעיה, וכו');
    :אישור הפעולה;
  }
else (לא)
  :סימון הדיווח כ'טופל';
endif

stop

@enduml
