@startuml
!theme vibrant

title פעילויות צפייה ביומני מערכת

start
:גישה למקטע "יומני מערכת / אנליטיקות";

:בחירת סוג יומן (מערכת, פעילות, וכו');

partition "עיון וניתוח" {
  :צפייה ברשימת הנתונים;
  if (סינון או חיפוש?) then (כן)
    :הזנת קריטריונים לסינון/חיפוש;
  else if (מיון?) then (כן)
    :בחירת עמודה למיון;
  else if (ייצוא?) then (כן)
    :לחיצה על כפתור הייצוא;
    :שמירת קובץ הנתונים (CSV/TXT);
  endif
}

stop

@enduml
